title: Notes
email: fierceinbattle@gmail.com
description: >-
  This is a site to host my markdown notes
baseurl: "/notes"
url: ""

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
